# Generated by Django 5.0.4 on 2024-04-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pereval_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coords',
            new_name='Cords',
        ),
    ]
