# Generated by Django 5.0.4 on 2024-04-07 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_coords_pereval_cords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pereval',
            name='cords',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.cords'),
        ),
        migrations.AlterField(
            model_name='pereval',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.level'),
        ),
    ]
