# Generated by Django 5.0.4 on 2024-04-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_rename_pereval_perevaladded_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cords',
            new_name='Coords',
        ),
        migrations.RenameField(
            model_name='perevaladded',
            old_name='cords',
            new_name='coords',
        ),
    ]
