# Generated by Django 5.0.4 on 2024-04-07 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_cords_coords_rename_cords_perevaladded_coords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perevaladded',
            old_name='time',
            new_name='add_time',
        ),
        migrations.CreateModel(
            name='PerevalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('pereval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.perevaladded')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
